version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shareit-postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../ShareIt/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - shareit-network

volumes:
  postgres_data:

networks:
  shareit-network:
    driver: bridge